### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cscherrer** [xukai92/nutsinjulia#2]
Hi @xukai92, I'd like to start a repository heavily based on your code, but with some modifications that lead to incompatibility. I don't see a license file. Is there one you prefer? I'd like to use MIT or BSD if possible. Thanks!

**Comment by xukai92** [comment]
Hi @cscherrer, I'm very sorry that I didn't check this repo after things were moved to Turing.jl. I guess this issue is out-of-date because Soss.jl now depends on DynamicHMC.jl. But many thanks for you attention here!
